cache:
  directories:
  - $HOME/.m2/repository

git:
  depth: 3

install: ./mvnw -V -DskipTests=true -Dgpg.skip=true -Psonatype-oss-release install

jdk:
- openjdk8
- openjdk9
- openjdk10
- openjdk11

language: java

script: ./mvnw verify
